version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "k1LoW"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3      
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "k1LoW"
